# useful when there are specific additional
# dependencies you want to be checked that are
# missing from your dependency files. Or for some
# reason Deadpendency is not detecting them.
additional-deps:
  typescript:
    # additional deps found in the package registry

# useful when you choose to depend on an unhealthy dependency.
ignore-failures:
  typescript:

additional-dependency-files:
  - path: other-package.json
    type: npm-package-json

rules-config:
  no-recent-package-release:
    warn-at-months: 6
    # fail-at-months: 24 omitted to use the default
  no-recent-commit:
    warn-at-months: 12
    fail-at-months: 24
  few-yearly-commits: disabled # disable this one entirely

  single-recent-author: warn

  # these defaults are fine, so we don't change them

  repository-archived: fail
  repository-is-fork: warn
  package-deprecated: warn
